language: node_js
cache:
  yarn: false
  npm: false
services:
  - postgresql
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_2092b72ab2aa_key -iv $encrypted_2092b72ab2aa_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
install: yarn install
env:
  - NODE_ENV="test_travis"
    DATABASE_URL="postgres://postgres:postgres@localhost:5432/test_travis"
before_script:
  - yarn db:create && yarn db:migrate
script:
  - yarn lint && yarn build && yarn test
after_success: yarn coverage
deploy:
  - provider: script
    script:
      git clone https://github.com/fiuba-laboral-v2/deploy.git &&
      cd deploy &&
      yarn install &&
      NODE_ENV=production yarn deploy:backend
    on:
      branch: production
  - provider: script
    script:
      git clone https://github.com/fiuba-laboral-v2/deploy.git &&
      cd deploy &&
      yarn install &&
      NODE_ENV=staging yarn deploy:backend
    on:
      branch: staging
notifications:
  email:
    recipients:
      - llauromanuel@gmail.com
      - dylanalvarez1995@gmail.com
      - sebastian.e.blanco@gmail.com
