language: node_js
services:
  - postgresql
before_install:
  - openssl aes-256-cbc -K $encrypted_2092b72ab2aa_key -iv $encrypted_2092b72ab2aa_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
env:
  - NODE_ENV="test_travis"
    DATABASE_URL="postgres://postgres:postgres@localhost:5432/test_travis"
before_script:
  - yarn build
  - cp database.travis.yml config/database.yml
  - psql -c "CREATE DATABASE test_travis;" -U postgres
  - yarn db:drop && yarn db:create && yarn db:migrate
script:
  - yarn lint && yarn test
after_success: yarn coverage
deploy:
  - provider: script
    script:
      git clone https://github.com/fiuba-laboral-v2/deploy.git &&
      cd deploy &&
      yarn install &&
      NODE_ENV=production yarn deploy:backend
    on:
      branch: master
  - provider: script
    script:
      git clone https://github.com/fiuba-laboral-v2/deploy.git &&
      cd deploy &&
      yarn install &&
      NODE_ENV=staging yarn deploy:backend
    on:
      branch: staging
  - provider: script
    script:
      git clone -b feature/16-deploy https://github.com/fiuba-laboral-v2/deploy.git &&
      cd deploy &&
      yarn install &&
      NODE_ENV=staging yarn deploy:backend
    on:
      branch: feature/16-deploy
notifications:
  email:
    recipients:
      - llauromanuel@gmail.com
      - dylanalvarez1995@gmail.com
      - sebastian.e.blanco@gmail.com
