version: '3.4'
services:
  fiuba-laboral-v2-backend:
    build: .
    command: yarn pm2:start
    image: fiuba-laboral-v2-backend-img
    container_name: "fiuba-laboral-v2-backend"
    env_file:
      - .env
    ports:
      - 5006:5006
    restart: always
    depends_on:
      - fiuba-laboral-v2-backend-database-postgres
  fiuba-laboral-v2-backend-database-postgres:
    image: postgres:latest
    container_name: fiuba-laboral-v2-backend-database-postgres
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 5434:5432
    restart: always
    env_file:
      - .env
