apps:
  - script: ./dist/src/index.js
    name: "fiuba-laboral-v2-back-end"
    node_args: "-r ./tsconfig-paths-bootstrap.js"
    instances: max
    exec_mode: cluster
    watch: true
    max_memory_restart: 250M
